### PR TITLE
Ci/cd pipelines   issue #5

### PR DESCRIPTION
**Pull request by elidakirigo**
issue #5 

adding a node CI pipeline  that `npm installs` and `npm starts` on `push` and `pull requests`

### CODE REVIEW

**Comment by smitjiwani** [comment]
lgtm.

**Comment by elidakirigo** [comment]
we can add a few more codes in the future, like GitHub comments @smitjiwani

**Comment by smitjiwani** [comment]
That makes sense, won't be closing this issue, feel free to raise another pr regarding the same. Will merge these commits by EOD :)

**Comment by elidakirigo** [comment]
sure, @smitjiwani

**Pull request merged**
